package:
  name: lqtmoment
  version: "0.2.1"

source:
  path: .. 

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - lqtmoment = lqtmoment.main:main
    - lqtcatalog = lqtmoment.catalog_builder:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python >=3.8
    - numpy >=1.21.0,<2.0
    - pandas >=1.5.0
    - matplotlib >=3.5.0
    - scipy >=1.5.0
    - scikit-optimize >=0.10.0
    - obspy >=1.3.0
    - tqdm >=4.60.0
    - configparser >=5.0.0
    - openpyxl >=3.0.0
    - plotly >=5.20.0
    - kaleido>=0.1.0

test: 
  imports:
    - lqtmoment
  commands:
    - lqtmoment --help
    - lqtcatalog --help
  
abouttemperament:
  summary: "Compute seismic moment in LQT systems with advanced spectral fitting"
  licence: MIT 
  url: "https://github.com/bgjx/lqt-moment-magnitude"